### ISSUE TITLE
Alexa integration?

### ISSUE THREAD

**Issue by traiger** [jayrox/esp8266_ir_blaster#1]
Would you be interested in Alexa integration? Or do you do that through Home Assistant? I've looked into running a node.js server but it would be nice to program something to control my TV and my Roku.

Thanks!

**Comment by jayrox** [comment]
I currently use Home Assistant to integrate with Alexa. That said, I do think Alexa integration without Home Assistant possibly would make the barrier to entry lower and make it more generic for people to be able to choose. Before going that route, the sketch would need to be updated to be much more generic. That would allow it to be fitted to control things like a Roomba, TV and entertainment center without needing to deploy new code to the ESP8266. Again, this lowers the barrier to entry. I do have plans on updating the sketch to use `irsend.sendGC` instead of `irsend.sendRaw`. I think I'll do that tonight. I am also learning Blender to make a 3D printed case for the board.
